### ISSUE TITLE
Regarding LTI Oidc authentication and Deep Link

### ISSUE THREAD

**Issue by Rohi145** [dmitry-viskov/pylti1.3#1]
Hello,

we have a few questions:
1. Are we necessary to have platform private key for JWT generation which then verified the signature with the public key? If yes then how to get it, that will verify the signature with JWK set?
Because you are taking the same private key for both(means for platform private key and tools private key)
2. How to get us deep link return URL of any LMS for LTI 1.3(Ex.Blackboard)?

**Comment by dmitry-viskov** [comment]
@Rohi145 First of all - the current library is LTI implementation on the Tool side only (not Platform)
1.
Platform private key and tool private key - are different keys.

On the Tool side we just decode message without verification:
https://github.com/dmitry-viskov/pylti1.3/blob/1.0.0/pylti1p3/message_launch.py#L329
using public key that we get from the platform:
https://github.com/dmitry-viskov/pylti1.3/blob/1.0.0/examples/configs/game.json#L26

On the Tool side we may also generate two keys: private and public.
Private: https://github.com/dmitry-viskov/pylti1.3/blob/1.0.0/examples/configs/private.key
Public: https://github.com/dmitry-viskov/pylti1.3/blob/1.0.0/examples/configs/public.key 
Public key should be set on the platform side. It is used to validate messages from tool (when tool send to platform grades and etc)

>Because you are taking the same private key for both

Unfortunately i don't understand what Platform key do you mean and why it is the same as private key from example.

2.

>How to get us deep link return URL of any LMS for LTI 1.3(Ex.Blackboard)?

Unfortunately i don't understand your question. Deep link return url is set on the platform side. On the Tool side we get it from JWT body:
https://github.com/dmitry-viskov/pylti1.3/blob/1.0.0/tests/test_deep_link.py#L135

**Comment by Rohi145** [comment]
@dmitry-viskov 

Hi,

1. On the tool side, we just decode the message using the public key(i.e getting after app registration ex.https://github.com/dmitry-viskov/pylti1.3/blob/1.0.0/examples/configs/public.key). But before decode, we encode the message using some private key.
   So my question is that which private key is used to encode this message. Because tool private key is used for access token generation.
2. #
>  Unfortunately i don't understand your question. Deep link return url is set on the platform side. On the Tool side we get it from JWT body:
> https://github.com/dmitry-viskov/pylti1.3/blob/1.0.0/tests/test_deep_link.py#L135

I need to understand that, we will set a deep link return URL in the message body. So, to set this value we need deep link return URL.My question is that where we get this URL.For more explanation: In LTI 1.1 we are getting this value from tool i.e content_item_return_url.

**Comment by dmitry-viskov** [comment]
1.
>On the tool side, we just decode the message using the public key(i.e getting after app registration ex.https://github.com/dmitry-viskov/pylti1.3/blob/1.0.0/examples/configs/public.key)

This public.key is not used to decode messages from platform. We provide this key to the platform to decode tool messages. Public key to decode messages from platform usually is retrieved from the URL: https://github.com/dmitry-viskov/pylti1.3/blob/master/examples/configs/game.json#L6
or may be set as a constant:
https://github.com/dmitry-viskov/pylti1.3/blob/master/examples/configs/game.json#L7

2. https://www.imsglobal.org/spec/lti-dl/v2p0/
>When forming the deep linking request message, the platform includes a deep_link_return_url in the https://purl.imsglobal.org/spec/lti-dl/claim/deep_linking_settings claim. The tool MUST redirect the workflow to that URL once the user has completed the selection or creation portion of the overall flow.
Tool doesn't provide this value. You set it by yourself on the platform side.

3. Sorry. Unfortunately I have no experience with Blackboard. From the tool we provide public key: https://github.com/dmitry-viskov/pylti1.3/blob/1.0.0/examples/configs/public.key or the same in the JWK format: https://github.com/dmitry-viskov/pylti1.3/blob/1.0.0/examples/configs/public.jwk.json.
I may just share you settings that used to configure Canvas as a Platform:
![Screenshot 2019-08-19 в 16 47 44](https://user-images.githubusercontent.com/1876893/63270685-5306f980-c2a1-11e9-9dfe-77f2234fa944.png)

4. Unfortunately I have no experience Blackboard. Sorry

**Comment by Rohi145** [comment]
@dmitry-viskov ,

1. We only need to know that, JWK URL that is getting from the platform is used to decode message which is encoded by Private key(not tool private key) for signature verification?
Here, we are trying to ask about the platform private key because we are using elab.
2. In Canvas, you also need a deep link return URL. How to get this one on canvas?

**Comment by dmitry-viskov** [comment]
@Rohi145 your questions related to the implementation of some abstract platform. This project is particular Tool implementation. I may recommend you to find answers to your questions in the LTI 1.3 Spec: https://www.imsglobal.org/spec/lti/v1p3
