### ISSUE TITLE
[Flask] How to deploy into production environment

### ISSUE THREAD

**Issue by qerdcv** [dmitry-viskov/pylti1.3#126]
Hi!

Thank you for your library.

I have a question about how to deploy the LTI library with WSGI servers. I've tried to deploy it with Gunicorn or other methods described on the Flask deployment page, but I encounter an issue with nonce when deploying with more than one worker.

**Comment by hmoffatt** [comment]
From memory, you need to configure the Flask cache to fix this. https://github.com/dmitry-viskov/pylti1.3#flask-cache-data-storage. And you must use a cache that is shared between workers, like the file system cache.

**Comment by qerdcv** [comment]
Shared cache dir works, thanks!
