### ISSUE TITLE
Is this library maintained?

### ISSUE THREAD

**Issue by FeldrinH** [dmitry-viskov/pylti1.3#131]
Looking at the current state of this library, it seems that there haven't been any releases or commits for about 1.5 years, yet there are a number of bugs and feature requests that are clearly important to users, for example:

* https://github.com/dmitry-viskov/pylti1.3/issues/119
* https://github.com/dmitry-viskov/pylti1.3/issues/123

Also, the lack of support for async web frameworks is becoming increasingly important with the rise of frameworks like FastAPI in the last few years:

* https://github.com/dmitry-viskov/pylti1.3/issues/115

I am currently planning to develop a new custom LTI tool in Python and given all this I have the following question:

Is this library maintained? If yes, will it be getting new features or only bugfixes?

**Comment by dmitry-viskov** [comment]
hi @FeldrinH 

>Is this library maintained? If yes, will it be getting new features or only bugfixes?

Yes, but only bugfixes. Unfortunately I don't have free time for implementing new features + my current projects are not related to LTI/ed-tech.
