### ISSUE TITLE
Testing library with Blackboard

### ISSUE THREAD

**Issue by dmitry-viskov** [dmitry-viskov/pylti1.3#14]

**Comment by shurrey** [comment]
Hi Dmitry. I am already testing with Blackboard and Flask. So far working through the launch. Opening in a new window works fine. Working through launching in an iframe and playing with SameSite and cookies. woohoo. I plan to build a tutorial and check in an example to github.com/blackboard when I am finished. Happy to contribute back the config JSON if that would help.

**Comment by shurrey** [comment]
So far I have found that it works pretty easily if I open in a new window. 

If I serve in an iframe, the state cookie isn't set with SameSite=None or Secure. is_secure() is returning false for that link. For my testing, I have hard-coded to secure and it works. 

I have also found one use case in Blackboard where we send an LtiResourceLinkRequest and no ResourceLinkId. Again, for my testing, I have this check commented out. We have a ticket open to correct this, so I will test this again once those changes are in.

**Comment by dmitry-viskov** [comment]
hi @shurrey .

Good news that it is working with Blackboard!

Regarding cookies issue. If you are testing locally (i.e without HTTPS) unfortunately there is no cross browser way to launch your program inside iframe. It is related to [samesite issue in Chrome 80](https://blog.heroku.com/chrome-changes-samesite-cookie). Cookies inside iframe will be set only with `SameSite=None` + `Secure` param. But `Secure` cookies will be sent to the server only in case of HTTPS connection.
I may suggest to add special check where you try to save test cookie before `login` step (as it already done in the Flask example: https://github.com/dmitry-viskov/pylti1.3-flask-example/blob/master/game/app.py#L57) and ask user to open window in the new tab.
Please check Flask example: https://github.com/dmitry-viskov/pylti1.3-flask-example .
In case of HTTPS usage and Flask >= 1.0.0 all code will work fine so there is no need to update library:
https://github.com/dmitry-viskov/pylti1.3/blob/master/pylti1p3/contrib/flask/cookie.py#L40
In the future I'll try to add "cookies check"/"open new window" inside library.

Regarding `LtiResourceLinkRequest` - do you mean this: https://github.com/shurrey/pylti1.3/commit/0f36c1af5805e7f009df00a032a12c6d90846525 ?
It looks like Blackboard bug because `resource_link` is required param: https://www.imsglobal.org/spec/lti/v1p3#resource-link-claim 
[Here is](https://github.com/IMSGlobal/lti-1-3-php-library/issues/43#issuecomment-598741671) the same discussion. For this case I may suggest just to implement your own `MessageLaunch` class (extend it from base `MessageLaunch`) and skip `validate_message` step:

```
class ExtendedMessageLaunch(MessageLaunch):
....
    def validate_message(self):
        jwt_body = self._get_jwt_body()
        message_type = jwt_body.get('https://purl.imsglobal.org/spec/lti/claim/message_type', None)
        if not message_type:
            raise LtiException("Invalid message type")

        validators = get_validators()
        validated = False
        for validator in validators:
            if isinstance(validator, ResourceMessageValidator):
                continue
            if validator.can_validate(jwt_body):
                if validated:
                    raise LtiException("Validator conflict")
                validated = True
                res = validator.validate(jwt_body)
                if not res:
                    raise LtiException("Message validation failed")

        if not validated:
            raise LtiException("Unrecognized message type")

        return self
```

**Comment by shurrey** [comment]
Hi @dmitry-viskov Working backwards, it is definitely a bug. My team is responsible for LTI and Caliper at Blackboard and we are actively working on this fix, so shouldn't be long. For now, I just have a fork with the resource link commented out. No changes there for the library. Once we have that fixed, it should work as you have it. 

As for the cookie, I am running on a server with SSL and a valid certificate. Everything works as expected except the state cookie. When it calls from cookie.py to see if the OIDC launch is secure, it is returning false, so then the samesite bit never gets added and when the launch is validated, it fails with states don't match. 

The fork that you found is being used in a project I am working on so I can load with my hacks. LOL If we deem a change needs to be made, I will delete that fork and create a new one.

**Comment by dmitry-viskov** [comment]
hi @shurrey 

>As for the cookie, I am running on a server with SSL and a valid certificate. Everything works as expected except the state cookie. When it calls from cookie.py to see if the OIDC launch is secure, it is returning false,

hmmm, interesting.... how is it possible? there is ordinary `request.is_secure` from Flask: https://github.com/dmitry-viskov/pylti1.3/blob/master/pylti1p3/contrib/flask/request.py#L15
Did i missed something?
What example do you use for testing? is it [pylti1.3-flask-example](https://github.com/dmitry-viskov/pylti1.3-flask-example) or something custom?

**Comment by shurrey** [comment]
It is based on the flask example. I am doing some custom things, but nothing with the cookies or the state.

**Comment by dmitry-viskov** [comment]
hi @shurrey 

I've investigated the issue and seems that you are using flask test server with the reverse proxy (like nginx) for example. I've [changed](https://github.com/dmitry-viskov/pylti1.3-flask-example/commit/726c727d99e624e60a939c804ffbf6b27eba217a) example a little. Please check. probably now it will work.
Anyway it is not a bug inside library - just misconfiguration on the server side

**Comment by dmitry-viskov** [comment]
Of course this solution will work only in case if `X-Forwarded-Proto` header is passed from the reverse proxy

**Comment by shurrey** [comment]
ok, got my project working. I will test the changes today and report back.

**Comment by shurrey** [comment]
I have to update a bit of configuration to run on heroku, but with that done, I can launch into the game no problem. When it tries to use AGS, it is failing with an invalid timestamp.

```
HTTP response [https://bbworld.hopto.org/learn/api/v1/lti/courses/_3_1/lineItems/_24_1/scores]: 
400 - 
{
  "status":400,
  "message":"JSON parse error: Invalid date string: 2020-04-07T13:26:14.786962; nested exception is :
                          Invalid date string: 2020-04-07T13:26:14.786962 (through reference chain: 
                          [\"timestamp\"])",
  "extraInfo":"80b6fbcb56f6430887a5e01c49a0ef8d"
}
```
Based on issues I have seen with the REST API, I suspect that it requires the timezone (or Z) at the end of the timestamp.

Testing deeplinking and names and roles next.

**Comment by shurrey** [comment]
I have to update a bit of configuration to run on heroku, but with that done, I can launch the game in a new window no problem. When it tries to use AGS, it is failing with an invalid timestamp.

```
HTTP response [https://bbworld.hopto.org/learn/api/v1/lti/courses/_3_1/lineItems/_24_1/scores]: 
400 - 
{
  "status":400,
  "message":"JSON parse error: Invalid date string: 2020-04-07T13:26:14.786962; nested exception is :
                          Invalid date string: 2020-04-07T13:26:14.786962 (through reference chain: 
                          [\"timestamp\"])",
  "extraInfo":"80b6fbcb56f6430887a5e01c49a0ef8d"
}
```
Based on issues I have seen with the REST API, I suspect that it requires the timezone (or Z) at the end of the timestamp.

**Comment by dmitry-viskov** [comment]
@shurrey the standard `isoformat` is used here: https://github.com/dmitry-viskov/pylti1.3-flask-example/blob/master/game/app.py#L196. It is working fine with Canvas LMS and IMSGlobal certification site. But you may pass here any string value

**Comment by shurrey** [comment]
When I append 'Z' it works as expected. I can add a check if product_family_code == 'BlackboardLearn', or just add a config option to append_timezone. How would you prefer?

**Comment by shurrey** [comment]
With that small change, everything works as expected, both in a new window and in an iframe.

**Comment by dmitry-viskov** [comment]
@shurrey big thanks for your work!
