### ISSUE TITLE
Trying to test the LTI 1.3 Integration on a local canvas instance

### ISSUE THREAD

**Issue by rsajja79** [dmitry-viskov/pylti1.3#142]
I have a local instance of canvas running and I want to try the LTI 1.3 integration on that.

here is the config.json:
 
![image](https://github.com/user-attachments/assets/8046f256-5b33-4f0e-8219-5f6fb452217a)

I get this error:
![image](https://github.com/user-attachments/assets/473cb83e-81be-4286-ab57-e83b45161472)

This is the request its making: 127.0.0.1 - - [08/Aug/2024 22:42:52] "GET /login/?lti1p3_new_window=1&iss=https://canvas.instructure.com&login_hint=86157096483e6b3a50bfedc6bac902c0b20a824f&target_link_uri=http://127.0.0.1:3000/launch&lti_message_hint=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjYW52YXNfZG9tYWluIjoiMTcyLjI0LjI1My4xNDciLCJjb250ZXh0X3R5cGUiOiJDb3Vyc2UiLCJjb250ZXh0X2lkIjoxMDAwMDAwMDAwMDAwMiwiY2FudmFzX2xvY2FsZSI6ImVuIiwiaW5jbHVkZV9zdG9yYWdlX3RhcmdldCI6dHJ1ZSwiZXhwIjoxNzIzMTc1MjcxfQ.peO_KwIaNUAroVt9eRJsf6yAAS3dBKkzeZVF-0AP3CQ&client_id=10000000000003 HTTP/1.1" 500 -

I dont know why it is using "https://canvas.instructure.com" instead of the local instance of canvas as said in config.json file.

Did anyone else have this problem? Please help me understand what is going on here.

**Comment by hmoffatt** [comment]
I think this means you did not properly set your local hostname for Canvas in the Canvas config. There are multiple places it has to be set in order to change the issuer and the return URL.

**Comment by rsajja79** [comment]
I have fixed this. Now I get a scope error. "http://127.0.0.1:3000/launch?error=invalid_scope&error_description=A+requested+scope+is+invalid%2C+unknown%2C+malformed%2C+or+exceeds+the+scope+granted+by+the+resource+owner.+The+following+scopes+were+requested%2C+but+not+granted%3A+openid&state=state-1e1f1fc4-06cb-4dcd-955a-f7cbae6cc7ee" 


does this have anything to do with authorization? I'm not sure what or where it is coming from.
