### ISSUE TITLE
pylti1p3.exception.LtiException: Unable to find public key

### ISSUE THREAD

**Issue by rsajja79** [dmitry-viskov/pylti1.3#143]
In the message launch I get the "Unable to find Public Key error"

This is my config.json:     "https://canvas.instructure.com": [
        {
            "default": true,
            "client_id": "42980000000000326",
            "auth_login_url": "url",
            "auth_token_url": "url",
            "key_set": {
                "keys": [
                    {"e": "AQAB", "kid": "oiu5vkiSOwHDXL_sTKfF7XZTttawWU1aykcRWP9DAJ4", "kty": "RSA", "n": "2llEfqIwIc9zpWEXLkx7LtqxgnMemw9GEVBHUZE8b9pOwfNQLVZX4haHxxoZtuFSTWPYm3Jz_Arh1Cnb-nHcpEE3Tgv8Ob1ijbj9fsOrvbyFuBk9TRiaMmaVCPY7_7bEXkir-xaqQK5u5Urnl7uw-5rqs9j4oL_kBzI2hM_VFgRU1YOA0ZmRGCn71aao6ES0ET7QuRGHltUwy8DdPifwyDTtkCw9ZzmEVj7szu8J2U4K_2Gbc7nDMA72W8qezKxjtJCrWLx-WqjCx4t0h8K-DQjbtQFiXUQVOny_z-XF2jV3upgj5t9qrHcJO-2_2mN8Hm_OcKv96S9ijpjiDMQNX1Mjjl7GHGBpwMfRDVVGv_q2B-lsWvzMLl867lRoggq3RFTT6GGReFA_c4ejaPbQ42wkT-uYk6b85HNFro-Ua5uFyCBox4d6kiYEvo2rbq8kbjYzIS2_lGdyyQmGCodLFzEP1lTTZhJgQ8Eawd5wxXbWRuDSgqmjdsVHTvqvkoDDCaK0AyZyhVYxJsL2tWByXSCDDFAEufojErAw59KiQs6KxBzW8AU-kazjWXWm5ghQ1Nwal9nQSBr3UpzxYYMzAMWKR5adO0jlmMPusTtpIPgOB4ne4cDD2fVy7i-ycsv92vgD-XNfdbWb-T6DB33xy4Prl_1qn2F8PwBMMxIXMTM", "alg": "RS256", "use": "sig"}
                ]
            },
            "private_key_file": "jwtRS256.key",
            "public_key_file": "jwtRS256.key.pub",
            "deployment_ids": [
                "40163:38041f78513dda8ca2ef4fdf08549703ab1344c0"
            ]
        }
    ],

I have created the jwt keys using https://github.com/dmitry-viskov/pylti1.3/wiki/How-to-generate-JWT-RS256-key-and-JWKS 
ssh-keygen -t rsa -b 4096 -m PEM -f jwtRS256.key
# Don't add passphrase
openssl rsa -in jwtRS256.key -pubout -outform PEM -out jwtRS256.key.pub
cat jwtRS256.key
cat jwtRS256.key.pub

and to create JWK create

import json
from jwcrypto.jwk import JWK

f = open("jwtRS256.key.pub", "r")
public_key = f.read()
f.close()

jwk_obj = JWK.from_pem(public_key.encode('utf-8'))
public_jwk = json.loads(jwk_obj.export_public())
public_jwk['alg'] = 'RS256'
public_jwk['use'] = 'sig'
public_jwk_str = json.dumps(public_jwk)
print(public_jwk_str)

![image](https://github.com/user-attachments/assets/dfae10c4-6b99-450a-b763-10dc5793b70e)

Do anyone know where this is coming from?

**Comment by hmoffatt** [comment]
Is that your Canvas's key in the key_set? Why not use the key set URL instead?

**Comment by rsajja79** [comment]
Yes it is. Would that be the reason of the error? I’m not sure where the error is coming from. I have all the necessary data included.
