### ISSUE TITLE
I'm unable to read the message launch data

### ISSUE THREAD

**Issue by rsajja79** [dmitry-viskov/pylti1.3#144]
The launch and the redirect works properly. 

Whenever I try to read the launch_data i get 
![image](https://github.com/user-attachments/assets/b717b11c-7aca-4c8f-8ed1-843234a5d71a)
![image](https://github.com/user-attachments/assets/bc5422d1-6036-4fc2-9569-4f8b145a5bf7)

I'm not sure what I'm missing from this. Any information or guidance helps.

**Comment by hmoffatt** [comment]
That message implies you provided a public_key_set string, while the code is expecting a dict.

**Comment by rsajja79** [comment]
Is this in the config.json or what should I be looking at?

**Comment by hmoffatt** [comment]
Yes in config.json

**Comment by rsajja79** [comment]
![image](https://github.com/user-attachments/assets/a47d895d-ddbd-4745-a660-a792222f83fe)
This is my config.json, is there anything I am missing. The launch works and the redirect works. 

I just need to be able to access the launch_data to get the name and other metadata.

**Comment by hmoffatt** [comment]
It should be `key_set_url` not `key_set`. The latter is for providing the keys directly. The keys are required to validate the launch data.

**Comment by rsajja79** [comment]
Oh my god! How stupid of me. 

thank you so much, that fixes it. I just overlooked it. I appreciate your help and time.
