### ISSUE TITLE
teacher role present in get roles call, but message_launch.check_teacher_access returns false

### ISSUE THREAD

**Issue by ziaulrehman40** [dmitry-viskov/pylti1.3#150]
Hi there,

I might be doing something worng, but putting it in an issue so anyone else who is struggling can also benefit.
but the issue is:

```
roles = message_launch_data.get('https://purl.imsglobal.org/spec/lti/claim/roles', [])

Above line gives me: ['http://purl.imsglobal.org/vocab/lis/v2/institution/person#Administrator', 'http://purl.imsglobal.org/vocab/lis/v2/institution/person#Instructor', 'http://purl.imsglobal.org/vocab/lis/v2/institution/person#Student', 'http://purl.imsglobal.org/vocab/lis/v2/membership#Learner', 'http://purl.imsglobal.org/vocab/lis/v2/system/person#User']

But when i run:
message_launch.check_teacher_access()

It is false
```

Am i missing something or something is not working?

**Comment by ziaulrehman40** [comment]
UPDATE: If i am properly added as a teacher, this does return true, I think there is a difference in the teacher role i was getting without being added in the coursE(because i am canvas admin maybe?)
This is a bit confusing

**Comment by hmoffatt** [comment]
See the code - https://github.com/dmitry-viskov/pylti1.3/blob/master/pylti1p3/roles.py#L86

You have teacher role on the institution but not the context, which is what the code is looking for. Whether or not it's correct depends on your application.

**Comment by ziaulrehman40** [comment]
Thanks @hmoffatt, i think we can improve documentation. Closing the issue.
