### ISSUE TITLE
Wiki JWT page update

### ISSUE THREAD

**Issue by ssilverm** [dmitry-viskov/pylti1.3#17]
For Python 3
```
import json
from jwcrypto.jwk import JWK

f = open("jwtRS256.key.pub", "rb")
public_key = f.read()
f.close()

jwk_obj = JWK.from_pem(public_key)
public_jwk = json.loads(jwk_obj.export_public())
public_jwk['alg'] = 'RS256'
public_jwk['use'] = 'sig'
public_jwk_str = json.dumps(public_jwk)
print(public_jwk_str)
```

**Comment by ssilverm** [comment]
Since I can't update wiki pages I've pasted in working code for getting the JWK

**Comment by dmitry-viskov** [comment]
hi @ssilverm 

i don't see any troubles with the current wiki instruction:

<img width="1599" alt="wiki" src="https://user-images.githubusercontent.com/1876893/77344158-d0b54b00-6d43-11ea-8c11-8f5be4fd4700.png">

Public key is a text file. There is no need to open it as binary.
In the nearest future I'll add method to generate JWT into the library.

**Comment by ssilverm** [comment]
Yep, you are right.  Must've been in the wrong virtualenv.  Closing.
