### ISSUE TITLE
Some question about LTI 1.3

### ISSUE THREAD

**Issue by tuluxmu** [dmitry-viskov/pylti1.3#19]
Hi Dmitry,

I look up the document about LTI 1.3.
When I try to do OIDCAuthorization, I try to call API to https://canvas.instructure.com/api/lti/authorize_redirect, I can't find the specific parameters I should use, and don't know how I generate the parameter `state`.

Could you please spare some time to talk more?
[https://canvas.instructure.com/doc/api/file.lti_dev_key_config.html]
Many thanks,
Lucy

**Comment by dmitry-viskov** [comment]
@tuluxmu 

https://github.com/dmitry-viskov/pylti1.3/blob/master/pylti1p3/oidc_login.py#L47
