### ISSUE TITLE
Deployment ID in JSON

### ISSUE THREAD

**Issue by ssilverm** [dmitry-viskov/pylti1.3#2]
Heya,

First of all, thanks for making an awesome library!

I've been looking through the spec, and from our own usage, and I think deployment_id should be removed as a check in the JSON.  The deployment ID is sent back via the JWT already, and isn't part of the signing.  Having to go and check the deployment ID manually is going to be impossible for many vendors.

For example:  We make an LTI and install it in over 200 courses.  We would need to then get the autogenerated deployment ids from each course and add them to our JSON.

Faculty are also able to clone a course with our LTI installed.  That will change the deployment id, but we won't know that, so even though it's a valid install, our application won't work for them.

I suggest removing the deployment_id check, and just adding the deployment_id from the JWT to a session variable.

**Comment by dmitry-viskov** [comment]
hi @ssilverm.

I agree with you that validation of `deployment_id` may look weird but seems that it is requirement of lti1.3 spec:
https://www.imsglobal.org/spec/lti/v1p3#lti-deployment-id-claim

>For a given client_id, the deployment_id is a stable locally unique identifier within the iss (Issuer).
>
>The deployment_id is an essential attribute for tools to associate to an account. See the Tool Deployment section for more details.

I may suggest to avoid `deployment_id` validation with such workaround:

```python
from pylti1p3.contrib.django import DjangoMessageLaunch

class ExtendedDjangoMessageLaunch(DjangoMessageLaunch):

    def validate_deployment(self):
        return self
```

**Comment by dmitry-viskov** [comment]
@ssilverm Probably you are right but also I think that this concept with `deployment_id` can be interpreted differently. Examples:
1. https://lti-ri.imsglobal.org/ - it is site is intended to test Platform <-> Tool communication. And here deployment_id is required parameter:

>Add Deployment, same value as Platform Key above (ex: 1)

2. https://www.imsglobal.org/lti-certification-suite - Suite to check Platform/Tool implementation also provide deployment_id that must be set on the Tool side:
<img width="1206" alt="Screenshot 2019-08-27 в 1 43 42" src="https://user-images.githubusercontent.com/1876893/63728393-2ee08500-c86c-11e9-814a-6668b61ee782.png">

3. https://github.com/IMSGlobal/lti-1-3-php-library - it is certified PHP library: https://site.imsglobal.org/certifications/turnitin/38021/lti+1.3+php+library+example
It also contains the same json config structure and the same deployment_id validation.

So i still think that by default deployment_id validation should be enabled. Anyway I've suggested workaround how avoid this (see `ExtendedDjangoMessageLaunch` class above)

**Comment by ssilverm** [comment]
Thinking more about this, especially now that there is a Flask release,  what about something like this:
Adding `'*:*'` to the deployment json would allow all IDs to pass through.
```
class FlaskMessageLaunch(FlaskMessageLaunch):
    def validate_deployment(self):
        iss = self._get_iss()
        deployment_id = self._get_deployment_id()

        # Find deployment.
        deployment = self._tool_config.find_deployment(iss, deployment_id)
        if '*:*' in tool_conf._config[iss]['deployment_ids']:
            deployment = True
        if not deployment:
            raise LtiException("Unable to find deployment")

        return self
```

**Comment by ssilverm** [comment]
Just want to update you on a response from Canvas - the initial problem I was facing was because originally a deployment id was generated for each course even if installed at the account level.

This has now been fixed on Canvas's side.  Installing it everywhere will only generate one deployment id based on the area you installed it in.

Everything is now working as intended.

**Comment by afeld** [comment]
> I may suggest to avoid `deployment_id` validation with such workaround:
> 
> ```python
> from pylti1p3.contrib.django import DjangoMessageLaunch
> 
> class ExtendedDjangoMessageLaunch(DjangoMessageLaunch):
> 
>     def validate_deployment(self):
>         return self
> ```

Dropping in here to say that I'm working on a Tool that is free, and thus we don't care what deployment is using the site. Therefore, this workaround was perfect 👍
