### ISSUE TITLE
Facing difficulty integrating with Canvas

### ISSUE THREAD

**Issue by danishyasin33** [dmitry-viskov/pylti1.3#21]
Hi Dmitry, 

Thank you for the great work. 

However, I am facing difficulty integrating the setup with canvas, specifically in the step 2 of the authentication process.

If I set the auth_login_url our implementation-specific: `https://learn.acehsc.com.au/api/lti/authorize` 

Then I get the error `"message":"An error occurred.","error_code":"internal_server_error"`

This is the form data that gets posted to my tool\login at step 1:

```
iss: https://canvas.instructure.com

login_hint: c02ea24550b257158e3b4f8e1e077c79bb2ee590

client_id: 10000000000011

target_link_uri: https://acehsc.online/launch/

lti_message_hint: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXJpZmllciI6IjVjNTdlYWFlOTM5YjRmZDJjM2UxZWRmM2Y5ZjFkODVlMTQ2ZmNhNDJmMzhkY2NiMTk4NTQyNjBkMDE2OGE4ZTQ3NmM1NmQ2OTA4ZjBlNGI3MTU3MjJkYTc3YjQ4MGJiNmU4YjUxMDdlOThiYzRjZjM4YjU3ZTU0YzRmZTEwZTQzIiwiY2FudmFzX2RvbWFpbiI6ImxlYXJuLmFjZWhzYy5jb20uYXUiLCJjb250ZXh0X3R5cGUiOiJDb3Vyc2UiLCJjb250ZXh0X2lkIjoxMDAwMDAwMDAwMDA1NiwiZXhwIjoxNTk0MTEzNjE3fQ.Tf-bqiP5hJajFY0Y_6gkQrPF372Ussvn7ECeOzjF2V0

canvas_region: not_configured
```

This is what my tool returns while redirecting to the `https://learn.acehsc.com.au/api/lti/authorize`:

```
client_id: 10000000000011

login_hint: c02ea24550b257158e3b4f8e1e077c79bb2ee590

lti_message_hint: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXJpZmllciI6IjVjNTdlYWFlOTM5YjRmZDJjM2UxZWRmM2Y5ZjFkODVlMTQ2ZmNhNDJmMzhkY2NiMTk4NTQyNjBkMDE2OGE4ZTQ3NmM1NmQ2OTA4ZjBlNGI3MTU3MjJkYTc3YjQ4MGJiNmU4YjUxMDdlOThiYzRjZjM4YjU3ZTU0YzRmZTEwZTQzIiwiY2FudmFzX2RvbWFpbiI6ImxlYXJuLmFjZWhzYy5jb20uYXUiLCJjb250ZXh0X3R5cGUiOiJDb3Vyc2UiLCJjb250ZXh0X2lkIjoxMDAwMDAwMDAwMDA1NiwiZXhwIjoxNTk0MTEzNjE3fQ.Tf-bqiP5hJajFY0Y_6gkQrPF372Ussvn7ECeOzjF2V0

nonce: d644906d47504bb682d6f4ed71d689d86136d3c4c03211eab109027500258144

prompt: none

redirect_uri: https://acehsc.online/launch/

response_mode: form_post

response_type: id_token

scope: openid

state: state-061e1b4b-e187-42ae-97ff-cd525d8746a9
```

As you can see the `lti_message_hint` is the same, everything is right but it still returns `internal_server_error` . I've been scratching my head over this for the last three days and any help would be highly appreciated. 

If I set the `auth_login_url` to `https://canvas.instructure.com/api/lti/authorize_redirect` then I simply get `Invalid lti_message_hint` error.

My JSON configuration file is attached below with the generic canvas configuration, I've tried changing and trying out different combinations of settings to no avail.

```
{
     "https://canvas.instructure.com": {
        "default": true,
        "client_id": "10000000000011",
        "auth_login_url": "https://canvas.instructure.com/api/lti/authorize_redirect",
        "auth_token_url": "https://canvas.instructure.com/login/oauth2/token",
        "key_set_url": "https://canvas.instructure.com/api/lti/security/jwks",
        "key_set": null,
        "private_key_file": "private.key",
        "public_key_file": "public.key",
        "deployment_ids": ["6:48a8d8c493e8d2aa9ce833888b4721865af0e06e"]
     }
}

```

**Comment by dmitry-viskov** [comment]
hi @danishyasin33.

You should use your canvas domain (https://learn.acehsc.com.au as i understand) as part of `auth_login_url`, `auth_token_url` and `key_set_url`.

**Comment by danishyasin33** [comment]
Hi @dmitry-viskov,

Thank you for your quick response. 

If I try to access the public jwks link with my canvas domain then it results in a `internal_server_error`. 

Do you have any idea why that would be? Screenshot attached. 
![image](https://user-images.githubusercontent.com/47951155/86796750-586f5d00-c088-11ea-8335-7533001373d5.png)

**Comment by dmitry-viskov** [comment]
@danishyasin33 looks like misconfiguration of your local canvas instance.
If you check SAAS Canvas: https://canvas.instructure.com/api/lti/security/jwks - this URL doesn't require authorization and working fine. You may check Canvas in Docker and it also working correct: https://github.com/instructure/canvas-lms/wiki/Quick-Start#setup

**Comment by danishyasin33** [comment]
I am also of the same opinion. 

The hosting provider wasn't being helpful. I am pursuing this with them. 

Thank you for your insightful response. I've been scratching my head around this for two days now.

**Comment by danishyasin33** [comment]
In this official [guide ](https://github.com/instructure/canvas-lms/blob/182f7411db23750e33cae6d360709f5bbf00fb3c/doc/api/lti_dev_key_config.md#config-in-tool) on canvas' GitHub, they state that the public JWK's URLs are environment-specific and not domain-specific.

They are explaining that the following URL will be used for all cloud hosted canvas instances: 

`https://canvas.instructure.com/api/lti/security/jwks`

So, shouldn't we be using this? What do you think?

**Comment by dmitry-viskov** [comment]
if you using canvas in docker the url is http://docker.host/api/lti/authorize_redirect . If you are using Canvas SaaS the url is https://canvas.instructure.com/api/lti/authorize_redirect. If you are using your ouwn host the URL is http://your.own.host//api/lti/authorize_redirect

**Comment by danishyasin33** [comment]
You were right. The issue was with the jwks URL of my canvas instance. 

The issue was resolved by copying the original dynamic_settings.yml from the canvas LMS GitHub repository to my own instance. 

After this, the JWKs and other URLs started working as intended.

**Comment by danishyasin33** [comment]
Hi Dmitry, 

So while trying to get the access_token for AGS services, the request to get the access token from my canvas instance is failing. 
The code raises an LTI exception with a 500 error with no conclusive error. 

So, I extracted the `auth_url` + the `auth_request` data and manually sent a request to my canvas instance by using [API tester](apitester.com).

This results in a more informative error: 
```{"error":"unsupported_grant_type","error_description":"The grant_type you requested is not currently supported"}```

You can check my test [here](https://apitester.com/shared/checks/571d389ed6bd4873905ecf8c9914318a).

I believe that something is wrong with my canvas instance and it's not accepting the `grant_type`, what do you think? Maybe the canvas isn't updated or the setup.

**Comment by danishyasin33** [comment]
Nevermind my earlier message. 
The issue resolved itself after I replaced the public JWK URL with the pasted JWK in the developer's key.
Canvas is weird.
