### ISSUE TITLE
add functions to check for roles

### ISSUE THREAD

**Issue by lsloan** [dmitry-viskov/pylti1.3#23]
I'd like to see functions for `is_instructor()`, `is_teaching_assistant()`, `is_learner()`, etc.  It seems these need to be implemented in each application that supports LTI, so it would be nice to have them as part of this module.

**Comment by ssilverm** [comment]
This is what we are using in both our Flask and Django apps:

```
role_urls = {
    'admin': "http://purl.imsglobal.org/vocab/lis/v2/membership#Administrator",
    'admin_inst': "http://purl.imsglobal.org/vocab/lis/v2/institution/person#Administrator",
    'instructor': "http://purl.imsglobal.org/vocab/lis/v2/membership#Instructor",
    'student': "http://purl.imsglobal.org/vocab/lis/v2/membership#Learner",
    'ta': "http://purl.imsglobal.org/vocab/lis/v2/membership/Instructor#TeachingAssistant",
}

class ExtendedDjangoMessageLaunch(DjangoMessageLaunch):

    def is_instructor(self):
        roles = self.get_launch_data().get('https://purl.imsglobal.org/spec/lti/claim/roles')
        return role_urls['instructor'] in roles and role_urls['ta'] not in roles

    def is_ta(self):
        roles = self.get_launch_data().get('https://purl.imsglobal.org/spec/lti/claim/roles')
        return role_urls['ta'] in roles

    def is_student(self):
        roles = self.get_launch_data().get('https://purl.imsglobal.org/spec/lti/claim/roles')
        return role_urls['student'] in roles

    def is_admin(self):
        roles = self.get_launch_data().get('https://purl.imsglobal.org/spec/lti/claim/roles')
        return role_urls['admin'] in roles or role_urls['admin_inst'] in roles

```

**Comment by libre-man** [comment]
[This](https://github.com/CodeGra-de/CodeGra.de/blob/master/psef/lti/v1_3/roles.py) is what we are using in our app (AGPL-v3 licensed). However, our experience is that the more customizable LMSes (Moodle for example) will use different names for things, and the spec is also pretty lenient in this area. So I don't think that actually adding this to the library is a very good idea.

**Comment by lsloan** [comment]
> This is what we are using in both our Flask and Django apps:

Similar thing here.  It seems reasonable that this logic could be part of this module so we all don't need to write the same thing in our applications.  It should be done in an extensible way, so if we have some reason to change the logic for a specific use case, it's easy to do.

This issue is in the same spirit as the other one I opened, #22 (define standard LTI role URIs).

**Comment by lsloan** [comment]
> [This](https://github.com/CodeGra-de/CodeGra.de/blob/master/psef/lti/v1_3/roles.py?rgh-link-date=2020-08-04T16%3A23%3A45Z) is what we are using in our app (AGPL-v3 licensed). 

I like the way you define the base URI and refer to it as part of the other URIs later.

**Comment by dmitry-viskov** [comment]
hi @lsloan . I've added built-in functions to check user's role after LTI launch:
https://github.com/dmitry-viskov/pylti1.3#check-users-role-after-lti-launch
Here is internal API:
https://github.com/dmitry-viskov/pylti1.3/blob/master/pylti1p3/roles.py

It is basic version. Pull requests are welcome 🙂

**Comment by ssilverm** [comment]
Heck yeah!  Thanks @dmitry-viskov
