### ISSUE TITLE
Detect Transient LTI Launch

### ISSUE THREAD

**Issue by ClaytonTurner** [dmitry-viskov/pylti1.3#26]
It would be nice if the MessageLaunch class had the ability to detect Transient LTI Launches.

The function could be something like `message_launch.check_transient()`

This is useful for detecting impersonation of users in Learning Management Systems. I believe the role claim comes through as `"http://purl.imsglobal.org/vocab/lis/v2/institution/person#Transient"`.

IMS Information: http://www.imsglobal.org/lti-when-user-not-real-user

If this change is deemed valid, then I would be happy to help in implementing this change.

**Comment by dmitry-viskov** [comment]
hi @ClaytonTurner . I've read IMS doc and this feature looks interesting. Do you know where this feature is already  implemented (i mean one of the popular LMS like Canvas, Blackboard, D2L and etc)? Usually I check all LTI features in the Canvas LMS but didn't see this feature there

>I would be happy to help in implementing this change.
it would be great. I think to implement this feature we should:

1. Define new role here: https://github.com/dmitry-viskov/pylti1.3/blob/master/pylti1p3/roles.py . Something like:
```
class TransientRole(AbstractRole):
    _common_roles = ('Transient',)  # type: tuple
    _system_roles = ('Transient',)  # type: tuple
    _institution_roles = ('Transient',)  # type: tuple
    _context_roles = ('Transient',)  # type: tuple
```

2. Add new method to the `MessageLaunch` class:
```
def check_transient(self):
    # type: () -> bool
    jwt_body = self._get_jwt_body()
    return TransientRole(jwt_body).check()
```

Thanks.

**Comment by ClaytonTurner** [comment]
@dmitry-viskov 
So I haven't seen this implemented in Canvas or Blackboard. I'm unsure about other major LMS's, to be honest, but I was more trying to get aligned to the spec itself.

Blackboard _should_ be doing this, but instead (in LTI 1.0/1.1 launches I've seen, at least) sends in `_previewuser` in its `custom_person_username` parameter (and potentially in other fields) to signify impersonation.

**Comment by ClaytonTurner** [comment]
Added those changes on a PR here: https://github.com/dmitry-viskov/pylti1.3/pull/27

**Comment by dmitry-viskov** [comment]
@ClaytonTurner thanks for the contribution! In the nearest future i'll release new minor version (1.8.2) with this addition

**Comment by hmoffatt** [comment]
I don't think any LMS is sending this still. Some of them add _previewuer, some have a fixed first/last for the student preview user and some of them just change roles without any hint as to why.
