### ISSUE TITLE
Invalid Nonce with Nginx + uWSGI

### ISSUE THREAD

**Issue by ssilverm** [dmitry-viskov/pylti1.3#28]
Hey All,

Trying to deploy a Django <-> uWSGI <-> Nginx application using pylti1.3 and whenever I put nginx in front of the application I get an Invalid Nonce error.

It's on AWS, nginx on http, ALB is https doing http-https conversion.

Any thoughts?

It works fine using Django built in server and uwsgi as the http server.

**Comment by dmitry-viskov** [comment]
hi @ssilverm .
i think you try to use LTI inside iframe and because of browser restrictions session-id cookie can't be set.
Please see instructions how to avoid this restrictions: https://github.com/dmitry-viskov/pylti1.3#cookies-issue-in-the-iframes

**Comment by ssilverm** [comment]
Thanks @dmitry-viskov !  Setting up the cache in Django fixed it.

**Comment by carpiodanielj** [comment]
Hi @ssilverm . I'm facing the same issue but in my case I'm using a Flask + Gunicorn app that is running with Docker and deployed on AWS EC2 with NGINX as web server. The code for the app is in this url [https://github.com/blackboard/BBDN-UEF-Python](url)
When I tested the code using ngrok [https://ngrok.com/](url) pointing to my localhost everything is working fine, but when I tested on EC2 with the configuration described above it gives me the error message "Invalid nonce".
I think that maybe something is missing in the configuration of my ngnix, could you please share me your config file.

Thanks in advance.
