### ISSUE TITLE
Grammar errors in documentation

### ISSUE THREAD

**Issue by shinsean** [dmitry-viskov/pylti1.3#30]
While reading through the README documentation for this library, I noticed there were a couple of minor grammatical errors that could be fixed to improve documentation readability.

I can detail what errors I noticed and/or make a PR with the corrections.

**Comment by dmitry-viskov** [comment]
hi @shinsean .

PR are welcome!

Thanks

**Comment by dmitry-viskov** [comment]
Related PR: https://github.com/dmitry-viskov/pylti1.3/pull/36

**Comment by dmitry-viskov** [comment]
@shinsean thanks for your contribution!
