### ISSUE TITLE
Existance of More Extensive Documentation?

### ISSUE THREAD

**Issue by ForrestPackard** [dmitry-viskov/pylti1.3#31]
I am trying to learn this library, and am having difficulty understanding parts of it. Is there any further documentation than what was included in the README? Some explanation of the individual classes and important functions would be beneficial to my efforts in understanding this library.

**Comment by dmitry-viskov** [comment]
hi @ForrestPackard . The goal of the README is to describe public API. I don't see any reason to include somewhere how internal structures works. You may just open code and investigate anything (there is no any magic - it is really simple).
If you need examples - here they are:
Django: https://github.com/dmitry-viskov/pylti1.3-django-example
Flask: https://github.com/dmitry-viskov/pylti1.3-flask-example
Also you may read official LTI 1.3 Specification: https://www.imsglobal.org/spec/lti/v1p3

**Comment by ForrestPackard** [comment]
OK, thanks for the reply and the help @dmitry-viskov ! The advise and resources are also much appreciated and I will work to utilize them.
