### ISSUE TITLE
Failed to get auth token for NRPS

### ISSUE THREAD

**Issue by Aamirsohel** [dmitry-viskov/pylti1.3#38]
Hi @dmitry-viskov ,
I was able to call get_members earlier but now I facing server error in both canvas and brightspace setup.

Here is the payload :

`{'grant_type': 'client_credentials', 'client_assertion_type': 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer', 'scope': 'https://purl.imsglobal.org/spec/lti-nrps/scope/contextmembership.readonly', 'client_assertion': <jwt_val>'}`

Error Message :

![image](https://user-images.githubusercontent.com/24321588/113502222-7b13a100-9548-11eb-9231-9e164de33e3d.png)

**Comment by dmitry-viskov** [comment]
504 Gateway Timeout error
