### ISSUE TITLE
nonce invalid

### ISSUE THREAD

**Issue by tudesc** [dmitry-viskov/pylti1.3#41]
Hi,
I put your demo project in Brightspace.
Somtimes it works, I see the game.hml.  other times , refresh, I get an nonce exception

Do you have any suggestions how to fix this?

Regards, Marcel

**Comment by dmitry-viskov** [comment]
hi @tudesc 

I may assume that you use non-secure HTTP connection. Nonce exception may happen because you use default framework's session mechanism through HTTP. Try to use `cache data storage` instead:
https://github.com/dmitry-viskov/pylti1.3#django-cache-data-storage

**Comment by dmitry-viskov** [comment]
>You may also have troubles with the default framework sessions because the pylti1p3 library can't control your framework settings connected with the session ID cookie. Without necessary settings, the user's session could be unavailable in the case of iframe usage. To avoid this, it is recommended to change the default session adapter to the new cache adapter (with a memcache/redis backend) and as a consequence, allow the library to set its own LTI 1.3 session id cookie that will be set with all necessary params like Secure and SameSite=None.

**Comment by tudesc** [comment]
No, i used a secure https connection.

 

Van: Dmitry Viskov ***@***.***> 
Verzonden: vrijdag 23 april 2021 00:36
Aan: dmitry-viskov/pylti1.3 ***@***.***>
CC: tudesc ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [dmitry-viskov/pylti1.3] nonce invalid (#41)

 

hi @tudesc <https://github.com/tudesc> 

I may assume that you use non-secure HTTP connection. Nonce exception may happen because you use default framework's session mechanism through HTTP. Try to use cache data storage instead:
https://github.com/dmitry-viskov/pylti1.3#django-cache-data-storage

**Comment by dmitry-viskov** [comment]
@tudesc You didn't provide any details / stack traces / steps so unfortunately i don't understand you issue.

I may just assume that you try to refresh LTI page that was opened in the new tab and `nonce` can't be found in session because session cookie becomes invalid and there could be a lot of reasons why it happens.

**Comment by tudesc** [comment]
When using django-cache-data-storage it work!
Thanks Dmitry
