### ISSUE TITLE
get grades

### ISSUE THREAD

**Issue by tudesc** [dmitry-viskov/pylti1.3#43]
Hi Dimitry,

I have a connection with a brightspace instance and try to retrieve grades.
I now receive a HTTP response [https://auth.brightspace.com/core/connect/token]: 400 - {"error":"invalid_grant","error_description":"Error validating assertion:

I just some code found in your test script.

{{{
    if not message_launch.has_ags():
        raise Exception("Don't have assignments and grades!")
    else:

        score_line_item = LineItem()
        score_line_item.set_tag('score') \
            .set_score_maximum(100) \
            .set_label('Score')

        scores = message_launch.validate_registration().get_ags().get_grades(score_line_item)

}}}

**Comment by dmitry-viskov** [comment]
hi @tudesc

Unfortunately I didn't test this library with a brightspace so can't say you what is wrong. Looks like some misconfiguration

**Comment by dmitry-viskov** [comment]
Here is discussion regarding testing in D2L: https://github.com/dmitry-viskov/pylti1.3/issues/13
