### ISSUE TITLE
Correct "auth_login_url" for Moodle

### ISSUE THREAD

**Issue by martinzugnoni** [dmitry-viskov/pylti1.3#63]
I'm struggling to find the correct value for "auth_login_url" using Moodle. Can you provide some guidance? Thank you.

**Comment by martinzugnoni** [comment]
It's the OIDC redirect URL after successful login. Examples provided here (but Moodle is missing): https://github.com/dmitry-viskov/pylti1.3-django-example/blob/master/configs/game.json#L5

**Comment by hmoffatt** [comment]
It's `https://<root>/moodle/mod/lti/auth.php`. After you add the tool in Moodle, click the info button and it'll show you all the URLs along with the allocated client ID and deployment ID.

**Comment by martinsam** [comment]
From Moodle ( 3.11 ) after configure a tool manually : 

Url : /moodle311/mod/lti/toolconfigure.php

click on the icon
![Capture d’écran 2022-04-05 à 15 31 53](https://user-images.githubusercontent.com/34697/161767164-a1771767-f65b-4903-a84a-b9302b19f7e2.png)


It should look like this :

![Capture d’écran 2022-04-05 à 15 31 11](https://user-images.githubusercontent.com/34697/161767409-4960d310-7582-40d1-92ff-a2c75a0880fd.png)

**Comment by hmoffatt** [comment]
Please close this if resolved.

**Comment by martinzugnoni** [comment]
Thank you
