### ISSUE TITLE
Grade not sending comment

### ISSUE THREAD

**Issue by Alain1405** [dmitry-viskov/pylti1.3#64]
Grade allows to add a comment, but when the grade is sent it is converted to dictionary but the comment is left behind.

Here is where the grade is "serialised" https://github.com/dmitry-viskov/pylti1.3/blob/476556aa5b13da20be591b6aea4b4f61b85ea8fe/pylti1p3/assignments_grades.py#L62 and the comment field is not there https://github.com/dmitry-viskov/pylti1.3/blob/476556aa5b13da20be591b6aea4b4f61b85ea8fe/pylti1p3/lineitem.py#L168

**Comment by Alain1405** [comment]
A simple fix such like https://github.com/strata-kk/pylti1.3/pull/2 works on edX. Grade comments are correctly stored on the consumer.

**Comment by dmitry-viskov** [comment]
FIxed
