### ISSUE TITLE
allow caller to set HTTP User-Agent

### ISSUE THREAD

**Issue by hmoffatt** [dmitry-viskov/pylti1.3#67]
It would be useful to be able to provide custom HTTP headers, in particular User-Agent. Possibly the caller could provide an optional Requests session object to use.

We have seen LMSs use content filters that block requests with a User-Agent of 'python-requests'.

**Comment by dmitry-viskov** [comment]
@hmoffatt hi. ok, i'll consider this feature in the future releases.

**Comment by dmitry-viskov** [comment]
done

**Comment by dmitry-viskov** [comment]
https://github.com/dmitry-viskov/pylti1.3/commit/cd20df3a1a1f4748f20f8fb22d8eeb8760454732
