### ISSUE TITLE
AGS find_or_create_lineitem does not check scopes

### ISSUE THREAD

**Issue by hmoffatt** [dmitry-viskov/pylti1.3#68]
`AssignmentsGradesService.find_or_create_lineitem` does not check its scopes before making the service call to create a new lineitem. On Moodle the user can configure the tool to access to put scores to the default line item but not to create new lineitems.

**Comment by dmitry-viskov** [comment]
Was fixed in AGS refactoring

**Comment by dmitry-viskov** [comment]
Fixed in the new `1.12.0` version: https://pypi.org/project/PyLTI1p3/1.12.0/
