### ISSUE TITLE
AGS put_grade with no line item raises missing tag exception

### ISSUE THREAD

**Issue by hmoffatt** [dmitry-viskov/pylti1.3#69]
You can call put_grade() without a line item, and if none is provided in the message launch data, it will try to create one: https://github.com/dmitry-viskov/pylti1.3/blob/476556aa5b13da20be591b6aea4b4f61b85ea8fe/pylti1p3/assignments_grades.py#L49-L53

However, the one it creates has no tag, so find_or_create_lineitem raises an exception: https://github.com/dmitry-viskov/pylti1.3/blob/476556aa5b13da20be591b6aea4b4f61b85ea8fe/pylti1p3/assignments_grades.py#L174-L177

**Comment by dmitry-viskov** [comment]
I've made small refactoring of AGS.
I don't see any issues in such behaviour when `lineitem` is created automatically. But I agree that it could be unexpected in some cases. So signature of function was changed to 
`def put_grade(self, grade, lineitem=None, create_default_lineitem=True)`
You may control `lineitem` creation using last param.
Also I've removed such behaviour in `def get_grades(self, lineitem=None)` function. It will not create new `lineitem` automatically.

**Comment by dmitry-viskov** [comment]
`missing tag exception` was fixed

**Comment by dmitry-viskov** [comment]
Sorry, I decided that `Explicit is better than implicit` and removed `create_default_lineitem=True, default_lineitem_tag='default'` temporary arguments. So now if there is no passed/connected `lineitem` library will raise an Exception: `Can't find lineitem to put grade`. So an exception still takes place but with the other `message text`

**Comment by dmitry-viskov** [comment]
Updated in the new `1.12.0` version: https://pypi.org/project/PyLTI1p3/1.12.0/
