### ISSUE TITLE
504- Gateway Timeout

### ISSUE THREAD

**Issue by afnan** [dmitry-viskov/pylti1.3#79]
I am constantly getting Gateway Timeout. When same request is performed by another tool to same url with same parameters it succeeds.  I am on python 3.8

Success Using Insomnia 
![image](https://user-images.githubusercontent.com/2023923/169455300-354501bb-fe5a-4d38-be8f-b0f782382c3d.png)

Exception in the code
![image](https://user-images.githubusercontent.com/2023923/169455352-7b00c26e-042e-401f-b31a-78879054c723.png)

I am getting the data that has been passed to `requests.post(auth_url, data=auth_request)`

**Comment by hmoffatt** [comment]
It looks like the Blackboard jwttoken endpoint returned the 504. You could compare the data that is sent when it works versus when it doesn't. But it may just be their issue.

**Comment by afnan** [comment]
> It looks like the Blackboard jwttoken endpoint returned the 504. You could compare the data that is sent when it works versus when it doesn't. But it may just be their issue.

Thats the thing. The data is same but one request is sent from the library and another one from Insomnia

**Comment by hmoffatt** [comment]
developer.blackboard.com has 6 different IPs, so you could be hitting a different server. Also, are all the headers the same?

**Comment by afnan** [comment]
> developer.blackboard.com has 6 different IPs, so you could be hitting a different server. Also, are all the headers the same?

Wrote a simple python program and provided it the same data that library is sending to the same url and failing. The demo program works like charm. Here is the screenshot
![image](https://user-images.githubusercontent.com/2023923/169463984-d9987fcb-bfe6-4e70-8e0a-591c1f347726.png)

```
import requests
auth_request = {
            "grant_type": "client_credentials",
            "client_assertion_type": "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
            "client_assertion": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJVbzNJWWlSR0ZDYUhNNEg0S2lid095enAtRU9KWlAweXkwd0g3bk5VOEEifQ.eyJpc3MiOiI2NjkxNmZmYy03YjE5LTQ0MWEtYjE5Zi0yOGQxMzVmYjZjOWYiLCJzdWIiOiI2NjkxNmZmYy03YjE5LTQ0MWEtYjE5Zi0yOGQxMzVmYjZjOWYiLCJhdWQiOiJodHRwczovL2RldmVsb3Blci5ibGFja2JvYXJkLmNvbS9hcGkvdjEvZ2F0ZXdheS9vYXV0aDIvand0dG9rZW4iLCJpYXQiOjE2NTMwMjY2NTcsImV4cCI6MTY1MzAyNjcyMiwianRpIjoibHRpLXNlcnZpY2UtdG9rZW4tNWMyZGFlNjYtMDQ2Zi00YjYwLTg5ODYtMjYyZGQxOTA3YTNhIn0.BQSIQ8iHnQXG9tqi-k9yR8TqQkDT-IhWdoTp-lZvNJn7QhnVS8_3Q7Y8uOtBHR6aUH3NdgvOnmyPwF9q9EzbxdicjpCy5CswphvcT_R3nyrXzSDx7n4QjaZymwhVprQH0IOgD1l3x-9K8_x_xWxd4FHUILrBQtgP1vI2xvtMDVECaoTkd03ukpuT-57zVYOgS5248zLBDVg9nm5vR9TkkchvfdKhPsQSy8NKaUkAhJn04e7s2EJ5opTZwvii9WtROWQQqBkDhMJQrSZSbVVjn8dqDV7VigI72DF4SyQR9WrI4Zkv2Gh1fldftjDHNZt4eoJtgguqU7jfS4zYeueDhw",
            "scope": "https://purl.imsglobal.org/spec/lti-nrps/scope/contextmembership.readonly",
        }
response = requests.post("https://developer.blackboard.com/api/v1/gateway/oauth2/jwttoken",data=auth_request)
print(response)
response = response.json()
print(response)

```

**Comment by hmoffatt** [comment]
What about the HTTP headers then?

**Comment by afnan** [comment]
> What about the HTTP headers then?

Well, I have tried different headers. The mind-boggling thing for me is why the same line of code that works in a separate file does not work in the library. The only thing that could be if requests is being modified somewhere in the library. I could be wrong though but still trying to isolate the problem

**Comment by hmoffatt** [comment]
You could have cookies or headers set in a requests session that are different/absent in the test code.

**Comment by afnan** [comment]
> You could have cookies or headers set in a requests session that are different/absent in the test code.

That is what I am thinking. However, I could not find anything like that. This is the line where the program gets 504 https://github.com/dmitry-viskov/pylti1.3/blob/7474685aecc35d528b944caf05b28ea66ac6d204/pylti1p3/service_connector.py#L82

I will try to import requests as something else just to isolate it.

**Comment by afnan** [comment]
BB expects url encoded which it is sending. Tried couple of other headers
but no joy

**Comment by afnan** [comment]
Just an update. The issue was not the library but the threads. When the request was made BB went out to check jwks and since the server thread on my dev server was a single threaded instance it timed out. Running with gunicorn and 4 threads solved it.

**Comment by bhagwandas** [comment]
Thanks @afnan for taking effort to put back your update.

It helped me in finding fix for this issue:

https://github.com/instructure/canvas-lms/issues/2354#issuecomment-2296097205

So our pylti1.3 should always run with more than 1 thread/worker.

It should be in written in Readme of this lib.
