### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by robertasilvano** [dmitry-viskov/pylti1.3#84]
Hi from Brazil!

I really dont have any experience with servers and security, but following some tutorials I managed to make work a xampp server, where my moodle instance is running with a self generated certificate, to test my Tool, that it is also running with a self generated certificate. But i am facing some problem with the SSL part during the launch flow, in these routes:

```
@lti_routes.route(tool.configs.initiate_login_uri, methods=['GET', 'POST'])
def oidc_init():
    config = ToolConfJsonFile(r'RemoteLabFPGA\lti\utils\register_config.json')
    flask_request = FlaskRequest()
    launch_data_storage = FlaskCacheDataStorage(cache)
    login = FlaskOIDCLogin(request=flask_request, tool_config=config, launch_data_storage=launch_data_storage)
    return login.enable_check_cookies().redirect(tool.claims.redirect_uris[0])


@lti_routes.route(tool.configs.redirect_uri, methods=['GET', 'POST'])
def oidc_launch():
    config = ToolConfJsonFile(r'RemoteLabFPGA\lti\utils\register_config.json')
    flask_request = FlaskRequest()
    launch_data_storage = FlaskCacheDataStorage(cache)
    message_launch = FlaskMessageLaunch(request=flask_request, tool_config=config, launch_data_storage=launch_data_storage)
    message_launch_data = message_launch.get_launch_data()
    return redirect(url_for('lab_routes.target_link'))
```

During the first route, the flow makes a call to the redirect function, that calls the CookiesAllowedCheckPage function, and then makes de JS function, and reload the same route. During this process of reload this route, my page changes from secure connection with valide certificate to not secure connection but stills with a valide certificate. After this, in this second run in this route, the redirect function call the second route, making the launch. In this part, the flow always broke during the FlaskMessageLaunch, when trying to get_public_key for the validate_jwt_signature, saying that is a SSL problem, that I believe is caused from the changing in the connection type (but may be wrong lol).

```
self.validate()
File "RemoteLabFPGA\venv\lib\site-packages\pylti1p3\message_launch.py", line 284, in validate
return self.validate_state()\
File "RemoteLabFPGA\venv\lib\site-packages\pylti1p3\message_launch.py", line 671, in validate_jwt_signature
public_key = self.get_public_key()
File "RemoteLabFPGA\venv\lib\site-packages\pylti1p3\message_launch.py", line 559, in get_public_key
public_key_set = self.fetch_public_key(key_set_url)
File "RemoteLabFPGA\venv\lib\site-packages\pylti1p3\message_launch.py", line 540, in fetch_public_key
raise LtiException("Error during fetch URL " + key_set_url + ": " + str(e))
pylti1p3.exception.LtiException: Error during fetch URL https://localhost/moodle/mod/lti/certs.php: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /moodle/mod/lti/certs.php (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)')))
```

I really dont know if the problem is with the way I configured the pylti1.3 or the xampp + certificates, but would appreciate some help! I dont understand why the type of connection is changing during the reload.

**Comment by hmoffatt** [comment]
I think the problem is from requests rejecting the self-signed certificate on your Moodle instance.

See for example https://stackoverflow.com/questions/30405867/how-to-get-python-requests-to-trust-a-self-signed-ssl-certificate on how you can set an environment variable to tell requests how to trust your cert.

Or just get proper certificates from LetsEncrypt.

**Comment by robertasilvano** [comment]
Oh, i see! thank u so much!
