### ISSUE TITLE
Support for Resource Link Membership Service

### ISSUE THREAD

**Issue by cmurtaugh** [dmitry-viskov/pylti1.3#85]
According to the IMS spec, we can include a `rlid=<resource_link_id>` parameter in calls to the NRPS and the LMS will include an extra `message` block for each user which includes custom variables:
https://www.imsglobal.org/spec/lti-nrps/v2p0#resource-link-membership-service

I'm trying to figure out if pylti1.3 supports this already, or what changes would be needed in order to add support. @dmitry-viskov do you have any thoughts?

**Comment by gracewhitney** [comment]
I second this request.
