### ISSUE TITLE
Missing Roles Claim

### ISSUE THREAD

**Issue by carpiodanielj** [dmitry-viskov/pylti1.3#87]
Hi everyone.
I'm working with the version 1.7.0 and the folllowing exception is showing in log, causing the application returns "500 Internal Server Error".

> 1655474968765,    raise LtiException('Missing Roles Claim'),ecs/bbdn-uef-python-td/6bd75f20105a41f894ad17736f29fe9e
> 1655474968765,pylti1p3.exception.LtiException: Missing Roles Claim,ecs/bbdn-uef-python-td/6bd75f20105a41f894ad17736f29fe9e

I've decoded the JWT token and found that attribute "https://purl.imsglobal.org/spec/lti/claim/roles" in JSON has an empty array (check bellow image). In other cases this attribute should contain one item at least, but in this case there is no items and don't know why.

![image](https://user-images.githubusercontent.com/13338743/176925044-bf2653f7-c64f-4a8c-9655-bffff9fddd49.png)

Anyone can help me? Please.

**Comment by carpiodanielj** [comment]
@dmitry-viskov I've sent an email with the possible solution of this issue. Please could you check it and comment.

Thanks in advance.

![image](https://user-images.githubusercontent.com/13338743/177426284-2873893a-4078-4a9b-9b26-1ddd39fc3012.png)

**Comment by dmitry-viskov** [comment]
@carpiodanielj fixed in the new `1.12.0` version: https://pypi.org/project/PyLTI1p3/1.12.0/

**Comment by carpiodanielj** [comment]
Really thank you @dmitry-viskov
