### ISSUE TITLE
public key cache is unsafe

### ISSUE THREAD

**Issue by hmoffatt** [dmitry-viskov/pylti1.3#90]
The `MessageLaunch` class has the ability to cache public keys, with a fixed expiry time.

D2L appears to expire their keys approximately hourly, if you look at https://partners.brightspace.com/d2l/.well-known/jwks . They set the HTTP cache headers to indicate that the JWKs should not be cached (`cache-control: no-cache, no-store`). So an application using the public key cache might keep using an expired key until the fixed expiry time.

I think it is safer not to use the public key cache in MessageLaunch but to use `requests-cache` to cache the key set fetches instead. This way the HTTP headers are honoured. This is very easy to integrate, though it would be better if there was a way to pass a requests Session object into the library.

**Comment by dmitry-viskov** [comment]
closed because solution is implemented here: https://github.com/dmitry-viskov/pylti1.3/commit/cd20df3a1a1f4748f20f8fb22d8eeb8760454732

**Comment by hmoffatt** [comment]
I think it would be helpful to document the risk of the included public key cache functionality.
